#define APP_VERSION 0, 0, 0, 1
#define APP_VERSION_STRING "0.0.0.1"
#define APP_ORGANIZATION_NAME "ZJV"
#define APP_ORGANIZATION_DOMAIN "zjvideo"
#define MAIN_APPLICATION_NAME "Laser Welding"
#define APP_LEGAL_COPYRIGHT "ZJV"
